I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1067, in script
    Emma "(muttering to himself) Why is this happening? I can't get excited."
Exception: Sayer 'Emma' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1067, in script
    Emma "(muttering to himself) Why is this happening? I can't get excited."
  File "C:\Users\kusha\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\kusha\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Emma' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
HackJklu 1.0
Sun Apr 23 11:44:48 2023
